# Generated by Django 2.1.2 on 2018-10-30 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ppr_position_tier', models.IntegerField(default=-1)),
                ('ppr_flex_tier', models.IntegerField(default=-1)),
                ('half_position_tier', models.IntegerField(default=-1)),
                ('half_flex_tier', models.IntegerField(default=-1)),
                ('standard_position_tier', models.IntegerField(default=-1)),
                ('standard_flex_tier', models.IntegerField(default=-1)),
            ],
        ),
    ]
